Repository GSG-G11/Nova, pull requests merged in 2022-05, with the labels that each got.

#26 create admin auth middleware
  server/middlewares/auth/adminAuth.ts
Labels: Awaiting Review

#30 Login Backend
  .eslintrc.json
  babel.config.js
  client/.eslintrc.json
  client/src/App.js
  client/src/index.js
  package.json
  server/app.ts
  server/controllers/auth/login.ts
  server/controllers/index.ts
  server/database/Models/Interviewee.ts
  server/database/Models/Interviewer.ts
  server/database/Models/Schedule.ts
  server/database/Models/User.ts
  server/database/build.ts
  server/database/config.ts
  server/database/fakeData/users.json
  server/index.ts
  server/middlewares/errors/errorHandler.ts
  server/middlewares/errors/index.ts
  server/middlewares/errors/notFound.ts
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/tests/database.test.ts
  server/tests/routes.test.ts
  server/utils/CustomError/index.ts
  server/utils/index.ts
  server/utils/jwt/signToken.ts
  server/utils/validation/loginValidation.ts
  yarn.lock
Labels: Awaiting Review, Backend

#29 create User Auth Middelware
  server/middlewares/auth/adminAuth.ts
  server/middlewares/auth/index.ts
  server/middlewares/auth/userAuth.ts
  server/utils/index.ts
  server/utils/interfaces/RequestType.ts
  server/utils/interfaces/index.js
  server/utils/jwt/index.ts
  server/utils/jwt/verifyToken.ts
Labels: Done

#31 Redux setup with authentication methods
  client/src/index.js
  client/src/redux/features/auth/authService.js
  client/src/redux/features/auth/authSlice.js
  client/src/redux/store.js
  package.json
  tsconfig.json
Labels: Awaiting Review

#28 create checkAuth controller
  server/controllers/auth/checkAuth.ts
  server/controllers/index.ts
  server/middlewares/auth/index.ts
  server/routes/authRoutes.ts
  server/utils/index.ts
Labels: Done

#33 Check User Authentication
  .gitignore
  client/src/App.js
  client/src/index.js
  client/src/redux/features/auth/authService.js
  client/src/redux/features/auth/authSlice.js
  server/controllers/auth/checkAuth.ts
  server/middlewares/auth/adminAuth.ts
  server/middlewares/auth/userAuth.ts
  server/routes/authRoutes.ts
  server/utils/interfaces/RequestType.ts
  server/utils/jwt/index.ts
Labels: Awaiting Review, Frontend

#25 14 sign up backend
  client/public/novaLogo.png
  package.json
  server/app.ts
  server/controllers/authentication/checkAuth.ts
  server/controllers/authentication/login.ts
  server/controllers/authentication/signUp.ts
  server/controllers/authentication/validateEmail.ts
  server/controllers/index.ts
  server/database/build.ts
  server/middlewares/auth/index.ts
  server/middlewares/auth/userAuth.ts
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/interfaces/index.js
  server/utils/interfaces/index.ts
  server/utils/interfaces/signupInterface.ts
  server/utils/jwt/index.ts
  server/utils/jwt/signToken.ts
  server/utils/jwt/verifyToken.ts
  server/utils/sendEmailVerification/sendEmail.ts
  server/utils/validation/index.ts
  server/utils/validation/loginValidation.ts
  server/utils/validation/signupValidation.ts
  tsconfig.json
  yarn.lock
Labels: Request-Change

#27 add login in frontend
  .vscode/settings.json
  client/.eslintrc.json
  client/package.json
  client/src/App.js
  client/src/assets/Nova Logo.png
  client/src/components/Login/LoginButton.jsx
  client/src/components/Login/LoginForm.jsx
  client/src/components/Login/style.css
  client/src/redux/features/auth/authSlice.js
  client/src/redux/store.js
  server/tests/routes.test.ts
  server/utils/validation/loginValidation.ts
Labels: Request-Change

#39 Get Reviews of a specified user interviews
  server/controllers/index.ts
  server/controllers/users/getReviews.ts
  server/database/config.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/users.json
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
  server/utils/sendEmailVerification/sendEmail.ts
  server/utils/validation/queryValidation.ts
Labels: Awaiting Review, Backend

#18 Create Sign up form with Validaiton and fetch data
  client/src/App.js
  client/src/assets/Nova Logo.png
  client/src/assets/images/logo.png
  client/src/components/Forms/Login/LoginButton.jsx
  client/src/components/Forms/Login/LoginForm.jsx
  client/src/components/Forms/index.js
  client/src/components/Forms/signup/Form.jsx
  client/src/components/Forms/signup/SignupButton.jsx
  client/src/components/Forms/style.css
  client/src/components/Login/style.css
  client/src/components/index.js
  client/src/redux/features/auth/authSlice.js
  client/yarn.lock
  server/index.ts
Labels: Done

#38 Get User Info ById Controller
  server/controllers/index.ts
  server/controllers/users/getUserById.ts
  server/routes/index.ts
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/validation/index.ts
Labels: Awaiting Review, Backend

#40 Create Interview and Send email to both parties
  server/app.ts
  server/controllers/index.ts
  server/controllers/interview/createInterview.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/database/fakeData/schedule.json
  server/database/fakeData/users.json
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/routes/interviewRoutes.ts
  server/tests/routes.test.ts
  server/utils/email/interviewEmailTemplate.ts
  server/utils/index.ts
  server/utils/validation/interviewValidation.ts
  yarn.lock
Labels: Awaiting Review, Backend

#49 Add delete function to delete interview from database
  server/controllers/index.ts
  server/controllers/users/deleteInterview.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/routes/index.ts
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
Labels: Request-Change, Backend

#46 get interviews
  server/controllers/index.ts
  server/controllers/users/getInterviews.ts
  server/controllers/users/getReviews.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/users.json
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/validation/queryValidation.ts
Labels: Awaiting Review, Backend

#53 update profile info
  server/controllers/index.ts
  server/controllers/users/updateInfo.ts
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/updateInfoInterface.ts
  server/utils/validation/updateInfoValidation.ts
Labels: Awaiting Review, Backend

#45 Update the saved property in review
  server/controllers/index.ts
  server/controllers/users/updateSavedReview.ts
  server/middlewares/errors/errorHandler.ts
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
Labels: Done, Backend

#56 Create Static Profile Tabs Section
  client/src/App.js
  client/src/components/ProfileTabs/index.js
  client/src/components/ProfileTabs/style.css
Labels: Done, Frontend

#67 Get Availabe Time (days and hours)
  server/controllers/index.ts
  server/controllers/interview/getAvailableTime.ts
  server/database/Models/Schedule.ts
  server/database/fakeData/schedule.json
  server/routes/interviewRoutes.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/validation/getInterviewTimeValidation.ts
Labels: Done, Backend

#54 User Info Section
  client/package.json
  client/src/App.js
  client/src/components/Forms/Login/LoginButton.jsx
  client/src/components/Forms/Login/LoginForm.jsx
  client/src/components/UserInfo/index.js
  client/src/components/UserInfo/style.css
  client/src/components/common/LoadingSpinner/index.js
  client/src/index.js
  client/yarn.lock
  server/controllers/authentication/login.ts
  server/controllers/users/getUserById.ts
Labels: Awaiting Review, Frontend

#65 Get interviewer name through reviews
  server/controllers/users/getReviews.ts
  server/database/Models/Interviewee.ts
  server/database/fakeData/interviewees.json
  server/tests/routes.test.ts
Labels: Awaiting Review, Backend

#88 Create Footer Component
  client/src/App.js
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
Labels: Done, Frontend

#89 Create Resources Component
  client/src/App.js
  client/src/assets/images/Resources/icon0.png
  client/src/assets/images/Resources/icon1.png
  client/src/assets/images/Resources/icon2.png
  client/src/assets/images/Resources/icon3.png
  client/src/components/Resources/ResourceCard/index.js
  client/src/components/Resources/index.js
  client/src/components/Resources/style.css
  client/src/components/common/SectionIntro/index.js
  client/src/components/common/SectionIntro/style.css
Labels: In Progress, Frontend

#91 Add Section Intro Component and Active Members
  client/src/App.js
  client/src/assets/images/circle.png
  client/src/components/ActiveMembers/Member/index.js
  client/src/components/ActiveMembers/index.js
  client/src/components/ActiveMembers/style.css
  client/src/components/common/Footer/style.css
  server/controllers/users/getUsers.ts
  server/database/fakeData/interviewers.json
  server/database/fakeData/users.json
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
Labels: Done, Frontend

#93 82 signup
  .eslintrc.json
  server/controllers/authentication/signup.ts
  server/controllers/users/getUsers.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/interfaces/signupInterface.ts
  server/utils/validation/index.ts
  server/utils/validation/signupValidation.ts
Labels: Done, Backend

#60 Create update setting form
  client/src/components/ProfileTabs/index.js
  client/src/components/ProfileTabs/style.css
  client/src/components/Setting/index.jsx
  client/src/components/Setting/style.css
  client/src/components/index.js
Labels: Done, Frontend

#104 80 header
  client/src/App.js
  client/src/assets/images/header.png
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  server/database/build.ts
  server/tests/routes.test.ts
Labels: Done, Frontend

#106 81 how nova work
  client/src/App.js
  client/src/assets/images/actIt.png
  client/src/assets/images/getPaired.png
  client/src/assets/images/practice.png
  client/src/components/HowNovaWork/index.jsx
  client/src/components/HowNovaWork/style.css
Labels: Done, Frontend

#98 Create Partner Componet
  client/src/App.js
  client/src/assets/images/brands.png
  client/src/components/Partner/index.jsx
  client/src/components/Partner/style.css
Labels: Done, Frontend

#102 Create Happy Clients Reviews Component
  .vscode/settings.json
  client/src/App.js
  client/src/assets/images/client.png
  client/src/assets/images/square.png
  client/src/components/ClientReviews/SliderCard.jsx
  client/src/components/ClientReviews/index.jsx
  client/src/components/ClientReviews/style.css
Labels: Done, Frontend

#103 Create Join us Component
  client/src/App.js
  client/src/assets/images/joinus.png
  client/src/components/IntreviewerApp/index.jsx
  client/src/components/IntreviewerApp/style.css
  client/src/components/common/Footer/style.css
  yarn.lock
Labels: Done, Frontend

#108 add logout function
  server/controllers/authentication/logout.ts
  server/controllers/index.ts
  server/routes/authRoutes.ts
Labels: Done, Backend

#105 96 verfiy account page
  client/src/App.js
  client/src/components/ActiveMembers/Member/index.js
  client/src/components/ActiveMembers/index.js
  client/src/components/ProfileTabs/index.js
  client/src/components/Resources/Setting/index.jsx
  client/src/components/Resources/Setting/style.css
  client/src/components/Resources/index.js
  client/src/components/VerifyAccount/VerifyResult/index.js
  client/src/components/VerifyAccount/index.js
  client/src/components/VerifyAccount/style.css
  client/src/components/index.js
  server/database/fakeData/users.json
Labels: Done, Frontend

#101 add navbar
  client/src/App.js
  client/src/components/Forms/Login/LoginButton.jsx
  client/src/components/Forms/signup/SignupButton.jsx
  client/src/components/Forms/style.css
  client/src/components/Landing/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/components/Navbar/style.css
  client/src/redux/features/auth/authService.js
  client/src/redux/features/auth/authSlice.js
  server/controllers/authentication/login.ts
  server/tests/routes.test.ts
Labels: Done, Frontend

#61 Add Static Form with steps functionality
  .vscode/settings.json
  client/src/App.js
  client/src/components/Forms/Interview/Hours/index.js
  client/src/components/Forms/Interview/InterviewForm.css
  client/src/components/Forms/Interview/InterviewForm.js
  client/src/components/Forms/Interview/RadioInput/index.js
  client/src/components/Forms/Interview/Steps/Step.js
  client/src/components/Forms/Interview/Steps/StepFive.jsx
  client/src/components/Forms/Interview/Steps/StepFour.jsx
  client/src/components/Forms/Interview/Steps/index.js
  server/database/Models/Interviewee.ts
  server/database/Models/Interviewer.ts
  server/database/Models/Schedule.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/database/fakeData/schedule.json
  server/tests/routes.test.ts
  server/utils/validation/getInterviewTimeValidation.ts
  server/utils/validation/interviewValidation.ts
  server/utils/validation/signupValidation.ts
Labels: Done, Frontend

#97 Create Top Challenges Section
  client/src/App.js
  client/src/components/Challenges/Challenge/index.js
  client/src/components/Challenges/index.js
  client/src/components/Challenges/style.css
  client/src/components/Landing/index.jsx
Labels: Done, Frontend

#110 Admin Delete User
  server/controllers/users/deleteUser.ts
  server/routes/adminRoutes.ts
  server/routes/index.ts
Labels: Done, Backend

#112 111 admin accept interviewer
  server/controllers/admin/acceptInterviewer.ts
  server/controllers/index.ts
  server/database/Models/Interviewer.ts
  server/database/fakeData/interviewers.json
  server/database/fakeData/users.json
  server/routes/adminRoutes.ts
  server/utils/index.ts
  server/utils/validation/acceptInterviewerValidation.ts
  server/utils/validation/index.ts
Labels: Awaiting Review, Backend

#116 113 get users admin
  server/controllers/admin/getUsersAdmin.ts
  server/controllers/index.ts
  server/controllers/users/getUsers.ts
  server/routes/adminRoutes.ts
  server/tests/routes.test.ts
  server/utils/index.ts
  server/utils/validation/index.ts
  server/utils/validation/queryValidation.ts
Labels: Done, Backend

#117 Admin Dashboard
  client/src/App.js
  client/src/components/AdminDashboard/index.js
  client/src/components/AdminDashboard/style.css
  client/src/components/Landing/index.jsx
  client/src/components/UserInfo/index.js
Labels: Awaiting Review, Frontend

#119 Fix Frontend Actvie Members Problem
  client/src/components/ActiveMembers/Member/index.js
  client/src/components/ActiveMembers/index.js
  server/controllers/index.ts
  server/controllers/users/getInterviewers.ts
  server/database/fakeData/users.json
  server/routes/userRoutes.ts
  server/tests/routes.test.ts
Labels: Awaiting Review, Frontend

#122 Fix Signup issue
  client/src/components/Forms/signup/Form.jsx
  client/src/components/Forms/signup/SignupButton.jsx
  client/src/components/Forms/style.css
Labels: Awaiting Review, Frontend

#128 127 user info skeleton
  client/src/components/ActiveMembers/Member/index.js
  client/src/components/ActiveMembers/index.js
  client/src/components/Landing/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/components/UserInfo/index.js
  client/src/components/UserInfo/style.css
  server/controllers/users/getUserById.ts
Labels: Awaiting Review, Frontend

#59 Create Reviews Component
  client/.eslintrc.json
  client/src/App.js
  client/src/components/ProfileTabs/index.js
  client/src/components/ProfileTabs/style.css
  client/src/components/Review/index.jsx
  client/src/components/Review/style.css
  client/src/components/index.js
  client/yarn.lock
  server/controllers/users/getReviews.ts
  server/controllers/users/updateSavedReview.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/tests/routes.test.ts
Labels: Done, Frontend

#130 Visible form onclick or hide it on cancel
  client/package.json
  client/src/components/ActiveMembers/index.js
  client/src/components/Challenges/index.js
  client/src/components/Forms/Interview/InterviewForm.js
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/components/Navbar/index.jsx
  client/src/components/Navbar/style.css
  client/src/components/Resources/index.js
  client/src/components/UserInfo/index.js
  client/src/components/UserInfo/style.css
  client/src/components/common/CreateInterviewButton/index.js
  client/src/index.css
  client/src/index.js
  client/yarn.lock
Labels: Done, Frontend

#133 132 landing functions
  client/package.json
  client/src/components/Forms/Login/LoginButton.jsx
  client/src/components/Forms/Login/LoginForm.jsx
  client/src/components/Forms/signup/Form.jsx
  client/src/components/Forms/signup/SignupButton.jsx
  client/src/components/Forms/style.css
  client/src/components/Header/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/components/Navbar/style.css
  client/src/components/VerifyAccount/VerifyResult/index.js
  client/yarn.lock
Labels: Awaiting Review, Frontend

#48 Create cancal intrview controller
  client/yarn.lock
  package.json
  server/controllers/index.ts
  server/controllers/interview/cancelInterviews.ts
  server/controllers/interviewer/postAvailableGlobal.ts
  server/controllers/interviewer/postAvailableTime.ts
  server/database/Models/Interviewee.ts
  server/database/Models/Interviewer.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/routes/index.ts
  server/routes/userRoutes.ts
  yarn.lock
Labels: Request-Change

#135 Create Not Found
  client/src/App.js
  client/src/components/NotFound/index.js
  client/src/components/NotFound/style.css
Labels: Awaiting Review, Frontend

#141 Create Fake Data and Fix Tests
  client/src/components/Forms/signup/Form.jsx
  client/src/components/VerifyAccount/style.css
  server/controllers/authentication/signup.ts
  server/controllers/authentication/validateEmail.ts
  server/database/build.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/database/fakeData/schedule.json
  server/database/fakeData/users.json
  server/tests/routes.test.ts
  server/utils/sendEmailVerification/sendEmail.ts
  yarn-error.log
  yarn.lock
Labels: Awaiting Review, Backend

#120 Create Zoom Link
  client/src/App.js
  client/src/components/ActiveMembers/style.css
  client/src/components/Challenges/style.css
  client/src/components/ClientReviews/index.jsx
  client/src/components/ClientReviews/style.css
  client/src/components/Header/style.css
  client/src/components/HowNovaWork/index.jsx
  client/src/components/HowNovaWork/style.css
  client/src/components/IntreviewerApp/style.css
  client/src/components/LoadingHome/index.js
  client/src/components/Navbar/index.jsx
  client/src/components/Navbar/style.css
  client/src/components/Resources/style.css
  client/src/components/UserInfo/index.js
  client/src/components/UserInfo/style.css
  client/src/components/common/Footer/style.css
  client/src/components/common/SectionIntro/style.css
  client/src/index.css
  package.json
  server/app.ts
  server/controllers/interview/createInterview.ts
  server/database/Models/Interviewee.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/schedule.json
  server/database/fakeData/users.json
  server/routes/index.ts
  server/utils/email/interviewEmailTemplate.ts
  server/zoom/createMeeting.ts
  yarn.lock
  zoom/.babelrc
  zoom/.eslintrc
  zoom/corp.js
  zoom/favicon.ico
  zoom/helper.html
  zoom/index.html
  zoom/js/index.js
  zoom/js/meeting.js
  zoom/js/tool.js
  zoom/localhost.crt
  zoom/localhost.key
  zoom/logo.png
  zoom/meeting.html
  zoom/package.json
  zoom/webpack.config.dev.js
  zoom/yarn.lock
Labels: In Progress, Frontend, Backend

#68 62 upcoming interviews component
  client/.eslintrc.json
  client/src/components/ProfileTabs/index.jsx
  client/src/components/ProfileTabs/style.css
  client/src/components/UpcomingAndHistoryInterviews/AddReviewButton.jsx
  client/src/components/UpcomingAndHistoryInterviews/Form.jsx
  client/src/components/UpcomingAndHistoryInterviews/UpcomingAndHistoryInterviews.jsx
  client/src/components/UpcomingAndHistoryInterviews/style.css
  client/src/components/UserInfo/index.js
  client/src/components/common/index.js
  client/src/redux/features/auth/authSlice.js
  server/controllers/users/getInterviews.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/tests/routes.test.ts
Labels: In Progress, Frontend

#140 create email template for verify acount
  server/controllers/authentication/signup.ts
  server/tests/routes.test.ts
  server/utils/email/verifyEmail.ts
Labels: Awaiting Review, Backend

#143 Link Zoom Front with Back
  client/src/components/Partner/index.jsx
  client/src/components/ProfileTabs/style.css
  client/src/components/UpcomingAndHistoryInterviews/UpcomingAndHistoryInterviews.jsx
  client/src/components/UserInfo/index.js
  server/controllers/interview/createInterview.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
Labels: Awaiting Review, Frontend

#85 Create available time and date Component
  client/package.json
  client/src/components/Calender/index.jsx
  client/src/components/Calender/style.css
  client/src/components/Landing/index.jsx
  client/src/components/ProfileTabs/index.jsx
  client/src/components/ProfileTabs/style.css
  client/src/components/Setting/index.jsx
  client/yarn.lock
  server/routes/index.ts
  server/routes/interviewRoutes.ts
  server/utils/validation/queryValidation.ts
  yarn-error.log
  yarn.lock
Labels: Awaiting Review, Frontend

#144 Create Profile Component & fix setting fun
  client/src/App.js
  client/src/components/Profile/index.jsx
  client/src/components/ProfileTabs/index.jsx
  client/src/components/Setting/index.jsx
  client/src/components/UserInfo/index.js
  server/utils/validation/updateInfoValidation.ts
Labels: Done

#147 Add FavIcon
  client/public/favicon/android-chrome-192x192.png
  client/public/favicon/android-chrome-512x512.png
  client/public/favicon/apple-touch-icon.png
  client/public/favicon/favicon-16x16.png
  client/public/favicon/favicon-32x32.png
  client/public/favicon/favicon.ico
  client/public/favicon/site.webmanifest
  client/public/index.html
  client/src/App.js
  client/src/components/Forms/Login/LoginForm.jsx
  client/src/components/Landing/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/components/Profile/index.jsx
  client/src/components/ProfileTabs/style.css
  client/src/components/Setting/index.jsx
  client/src/components/UserInfo/index.js
  client/src/components/VerifyAccount/VerifyResult/index.js
  client/src/components/VerifyAccount/style.css
  client/src/redux/features/auth/authSlice.js
  server/controllers/authentication/login.ts
  server/tests/routes.test.ts
  server/utils/email/verifyEmail.ts
Labels: Awaiting Review

#149 Fix create interview
  client/src/components/Forms/Interview/InterviewForm.js
  client/src/components/Profile/index.jsx
  client/src/components/UpcomingAndHistoryInterviews/UpcomingAndHistoryInterviews.jsx
  server/controllers/interview/createInterview.ts
  server/database/Models/Interviewee.ts
  server/database/Models/Interviewer.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/database/fakeData/schedule.json
Labels: Awaiting Review, Frontend, Backend

#137 Update style
  client/src/assets/images/logo-removebg-preview.png
  client/src/assets/images/parpelsvg.png
  client/src/assets/images/svg.png
  client/src/assets/images/whiteLogo.png
  client/src/components/ActiveMembers/style.css
  client/src/components/AdminDashboard/index.js
  client/src/components/AdminDashboard/style.css
  client/src/components/Calender/index.jsx
  client/src/components/Calender/style.css
  client/src/components/Challenges/index.js
  client/src/components/Challenges/style.css
  client/src/components/ClientReviews/style.css
  client/src/components/Forms/Login/LoginForm.jsx
  client/src/components/Forms/style.css
  client/src/components/Header/index.jsx
  client/src/components/Header/style.css
  client/src/components/HowNovaWork/index.jsx
  client/src/components/HowNovaWork/style.css
  client/src/components/Landing/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/components/Navbar/style.css
  client/src/components/Partner/style.css
  client/src/components/Profile/index.jsx
  client/src/components/Profile/style.css
  client/src/components/ProfileTabs/index.jsx
  client/src/components/ProfileTabs/style.css
  client/src/components/Resources/style.css
  client/src/components/Review/index.jsx
  client/src/components/Setting/index.jsx
  client/src/components/Setting/style.css
  client/src/components/UpcomingAndHistoryInterviews/UpcomingAndHistoryInterviews.jsx
  client/src/components/UserInfo/index.js
  client/src/components/UserInfo/style.css
  client/src/components/common/Footer/style.css
  client/src/components/common/SectionIntro/index.js
  client/src/components/common/SectionIntro/style.css
  yarn.lock
Labels: In Progress

#131 Create join us App form
  client/src/components/IntreviewerApp/InterviewerApp.jsx
  client/src/components/IntreviewerApp/JoinUsBtn.jsx
  client/src/components/IntreviewerApp/StepFirst.jsx
  client/src/components/IntreviewerApp/StepSecond.jsx
  client/src/components/IntreviewerApp/index.jsx
  client/src/components/IntreviewerApp/style.css
  client/src/components/Setting/index.jsx
  yarn.lock
Labels: Awaiting Review, Frontend

#151 Replace Zoom SDK with Zoom App and sort interviews by created at
  client/src/components/Challenges/style.css
  client/src/components/UserInfo/index.js
  server/controllers/authentication/signup.ts
  server/controllers/interview/createInterview.ts
  server/controllers/users/getInterviews.ts
  server/database/Models/Interviewee.ts
  server/database/Models/Interviewer.ts
  server/database/fakeData/interviewees.json
  server/database/fakeData/interviewers.json
  server/database/fakeData/users.json
  server/zoom/createMeeting.ts
  zoom/.babelrc
  zoom/.eslintrc
  zoom/corp.js
  zoom/favicon.ico
  zoom/helper.html
  zoom/index.html
  zoom/js/index.js
  zoom/js/meeting.js
  zoom/js/tool.js
  zoom/localhost.crt
  zoom/localhost.key
  zoom/logo.png
  zoom/meeting.html
  zoom/package.json
  zoom/webpack.config.dev.js
  zoom/yarn.lock
Labels: Awaiting Review, Backend
