Repository GSG-G11/Nova, pull requests merged in 2022-04, with the labels that each got.

#5 4 setup project structure
  .gitignore
  README.md
  client/.eslintrc.json
  client/.gitignore
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/components/common/index.js
  client/src/components/index.js
  client/src/index.js
  client/src/pages/index.js
  client/src/redux/features/index.js
  client/src/redux/store.js
  client/yarn.lock
  example.env
  package.json
  server/.eslintrc.json
  server/app.ts
  server/controllers/index.ts
  server/database/config.ts
  server/index.ts
  server/middlewares/errors/index.ts
  server/middlewares/index.ts
  server/routes/index.ts
  server/tests/database.test.ts
  server/tests/routes.test.ts
  server/utils/validation/index.ts
  tsconfig.json
  yarn.lock
Labels: Request-Change

#19 finish from setup database schemas
  .vscode/settings.json
  client/yarn.lock
  package.json
  server/app.ts
  server/database/config.ts
  server/database/models/interviewee.ts
  server/database/models/interviewer.ts
  server/database/models/schedule.ts
  server/database/models/user.ts
  yarn.lock
Labels: Awaiting Review

#23 Custom Error and Error Handler
  client/.eslintrc.json
  server/.eslintrc.json
  server/app.ts
  server/middlewares/errors/errorHandler.ts
  server/middlewares/errors/index.ts
  server/middlewares/errors/notFound.ts
  server/utils/CustomError/index.ts
  server/utils/index.ts
Labels: Done
